version: "2"

linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
        text: "G304: Potential file inclusion via variable"
  enable:
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
  settings:
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          disabled: true
